- .github/ISSUE_TEMPLATE/feature_request.md
I've added a issue template for the features.
The echancement flag is selected by default.
And the template looks like this:
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
> feat: issue templates for features

- CONTRIBUTING.md
Added a CONTRIBUTING.md for describe  the commit and branch name convention
> doc: CONTRIBUTING.md

- gui/Makefile
- gui/include/GameDatas/Team.hpp
- gui/src/GameDatas/Team.cpp
I created the Team class.
This class is necessary for the Zappy to separate each players into teams.
To see what's needed in the class, see this issue: #32
> feat: Team class zappy gui

- gui/Makefile
- gui/include/Engine/Engine.hpp
- gui/include/Event/Event.hpp
- gui/include/Render/Render.hpp
- gui/src/Engine/Engine.cpp
- gui/src/Event/Event.cpp
- gui/src/Render/Render.cpp
- gui/src/main.cpp
I added the Class event.
I handle the following events in the scene:
- camera up by pressing space
- camera down by pressing left shift
- debug interface (fps, cam pos, cam target) by pressing F3
More details : #44
> feat: Event class for events up and down camera and debug display

- gui/include/GameDatas/GameData.hpp
- gui/src/Engine/Engine.cpp
- gui/src/GUIUpdater/GUIUpdater.cpp
- gui/src/GameDatas/GameData.cpp
- gui/tests/GUIUpdater/TestGUIUpdater.cpp
- gui/tests/GameDatas/TestGameData.cpp
I handle the server command **seg**, the end of the game.
When the GUI receive the command **seg**, it close the window.
More details : #72
> feat: handle seg command server (end of game)

- gui/src/Engine/Engine.cpp
This little pr update the player position at each server's ticks.
> feat: send messages for player position at each tick

- server/include/ai/cmd/command_ai.h
- server/src/ai/cmd/incantation/check_incantation.c
- server/src/ai/cmd/incantation/incantation_handler.c
- server/src/ai/cmd/incantation/update_status.c
- server/src/ai/stuck.c
- server/src/server/read/read_data.c
- server/tests/communication/communication_test.c
I've implemented system of incantation !
> feat: system of incantation

- ai/Makefile
- ai/src/AI.py
- ai/src/Enum/Action.py
- ai/src/Enum/Item.py
- ai/src/Network/API.py
- ai/src/Player/Inventory.py
- ai/src/Player/Player.py
- ai/src/Player/PlayerException.py
- ai/src/main.py
- ai/tests/MainTest.py
- ai/tests/Network/TestAPI.py
- ai/tests/Player/TestInventory.py
- ai/tests/Player/TestPlayer.py
- ai/tests/TestAI.py
I've added all the actions of the players and the handling of the responses of the server (with a system of callback function). I also added the AI class that contain the API and the Player class.
:warning: The current chooseAction of the player is for the moment only a radom because the logic isn't write for the moment but that will come next.
> Implement the Player actions

- .github/workflows/mirror.yml
- gui/Makefile
- gui/README.md
> Feature make install + trigger in ci

- gui/Makefile
- tests/gui/tests/Render/TestDecoration.cpp
I adding tests for Decoration class.
More details : #112
> feat: test for Decoration class

- .github/workflows/mirror.yml
- server/src/main.c
Fix the CI coding-style check, which has been broken during development.
> fix: CI coding-style check

- ai/src/AI.py
- ai/src/Player/Inventory.py
- ai/src/Player/Player.py
- ai/src/Player/PlayerException.py
- ai/src/main.py
- tests/ai/tests/Player/TestInventory.py
I've added the fork function and a infinite loop in case of death of our AI. It prevents the AI from dying and allows it to fill its entire team without having to restart the program several times.
> Implement auto filling of all available slots in the team

- gui/include/Config.hpp
This very complicated pr change the default render distance (almost 10) by 15.
> refactor: change default render distance and max value

- server/include/ai/team.h
- server/src/ai/cmd/other/fork_cmd.c
- server/src/ai/stuck.c
- server/src/ai/team.c
- server/src/gui/gui.c
I haved add the send of command tna when a new gui connect.
And I fix the apparition of egg (swith of random position) and add new function to add egg in fork command.
> Add tna command when gui connected and fix egg apparition

- server/include/gui/communication.h
- server/src/ai/ai.c
- server/src/gui/communication/pnw.c
- server/src/gui/gui.c
- server/src/server/write/write_data.c
I've sent all message in one row and not one per one !
> Fix communication beetween client !

- gui/include/Assets.hpp
I fixed the rotation of two types of flowers.
Before, they were in the ground, now, they're beautiful and not in the ground anymore.
Check this issue for more details: #176
> fix: The rotation of two flowers to be well placed

- ai/src/AI.py
- ai/src/Player/Player.py
I moved the select of the AI in a Thread so our AI can continue to think without being blocked by the "select".
> Remove the blocking "select" in AI

- ai/src/AI.py
- ai/src/Enum/Role.py
- ai/src/Player/Player.py
- ai/src/main.py
- tests/ai/tests/Player/TestPlayer.py
I've updated the way the AI knows whether it's leader or slave, now the assignment is added in-game via broadcast.
> Improvement of the assignement of the leader/slave role

- gui/Makefile
- gui/include/Engine/Engine.hpp
- gui/include/Event/AEvent.hpp
- gui/include/Event/Event.hpp
- gui/include/Event/IEvent.hpp
- gui/include/GUIUpdater/AGUIUpdater.hpp
- gui/include/GUIUpdater/GUIUpdater.hpp
- gui/include/GUIUpdater/IGUIUpdater.hpp
- gui/include/Parsing/IServerParser.hpp
- gui/include/Parsing/ServerParser.hpp
- gui/src/Engine/Engine.cpp
- gui/src/Event/AEvent.cpp
- gui/src/Event/Event.cpp
- gui/src/GUIUpdater/AGUIUpdater.cpp
- gui/src/GUIUpdater/GUIUpdater.cpp
- gui/src/Render/Decoration.cpp
I made the GUI code more c++ friendly.
In fact, i made more inheritance and abstractions of existing classes for the GUI.
With this changes, we can build more test, for the Network, the updater, etc..
To see more details, check this issue: #181
> Feat/make gui code more c++ friendly zappy gui

- ai/src/main.py
I removed the `True` parameter that was blocking the launch of the AI
> Remove unnecessary parameter to be able to launch the AI

- server/src/ai/ai.c
- server/src/ai/die.c
- server/src/gui/gui.c
I've added the food directly at the beginning !
> Added food directly at the beggining

- gui/include/Config.hpp
- gui/include/Network/Network.hpp
- gui/src/Engine/Engine.cpp
- gui/src/Network/Network.cpp
I close the GUI when the server connection is down.
To do that I check if the read of the server is 0.
More details : #196
> feat: close GUI if server connection down

- gui/src/Engine/Engine.cpp
- gui/src/GUIUpdater/GUIUpdater.cpp
- gui/src/GameDatas/GameData.cpp
I fixed the time unit uninitialized value + the conditions where T is <= 0
To see more details, check this: #203
> fix: Time Unit uninitialized value + wrong conditions

- server/src/gui/communication/sst.c
I've check the value of sst command, if it's 0 i return sbp command.
> SST command when, the sst required frequence 0

- server/include/ai/ai.h
- server/include/ai/cmd/command_ai.h
- server/include/server/server.h
- server/src/ai/ai.c
- server/src/ai/cmd/other/dead_cmd.c
- server/src/ai/die.c
- server/src/server/quit.c
- server/src/server/read/read_data.c
- server/src/server/run.c
- server/src/server/write/write_data.c
I've fix the fact to send dead to all ennemy when an AI died !
> fix: send dead to all ennemy

- server/src/ai/cmd/incantation/incantation_handler.c
- server/src/ai/cmd/incantation/level_up.c
- server/src/ai/cmd/incantation/update_status.c
- server/src/ai/stuck.c
I've fix the send of the message at the beginning to all IA et the send of end message to all AI !
> fix: incantation send response

- server/Makefile
- server/src/ai/cmd/broadcast/calcul_k.c
- server/src/gui/communication/pic.c
- server/src/gui/communication/pie.c
I've added missing free follow to the test with Marius AI
> fix: add missing free with Marius AI

- ai/src/AI.py
- ai/src/Player/Player.py
- ai/src/Utils/Message.py
- tests/ai/tests/Player/TestPlayer.py
I updated the AI communication with other AI to encrypt and secure the communication. Now the other AI won't be able to sabotage our exchange beetween AI.
:information_source:  The encryption key is the team name since only our equip know it :nerd_face: 
:shield: I added a checker to see if our message are being replicated, if that the case the AI will ignore the message.
> Encrypt communication via broadcast - Zappy AI

- gui/include/Event/Event.hpp
- gui/src/Event/Event.cpp
I bound all the keyboards inputs to GamePad inputs.
Now you can do everything you do with a keyboard with a GamePad, except closing the window ('coz it segfault).
> [!Note]
> I don't know if every type of GamePad is accepted by raylib or not
> feat: GamePad controller inputs

- server/include/parsing.h
- server/src/main.c
- server/src/parsing/arguments.c
- server/src/parsing/help.c
- tests/server/tests/parsing/help_test.c
I've update the usage message and print the message in case of error of parsing.
> update the usage message and call print_help in case of error of parsing

- ai/src/AI.py
- ai/src/Network/API.py
I added a buffer in the AI class to handle incomplete or fragmented data.
> Create a buffer for data received from the server - Zappy AI

- ai/src/AI.py
- ai/src/Enum/Mode.py
- ai/src/Player/Player.py
- tests/ai/tests/Player/TestPlayer.py
I've added:
- A reaction when the AI has a problem during elevation
- A reaction when the leader AI dies
- A broadcast attack to disrupt enemy AIs
> Improve AI algorithm to be more versatile - Zappy AI

- server/src/server/run.c
I've added the check of message list to send in all the gui and ai before set in the fd_set for a better logic of select.
> Check if the content to send for set the fd_set of write of select

- ai/src/Player/Inventory.py
- ai/src/Player/Player.py
- tests/ai/tests/Network/TestAPI.py
- tests/ai/tests/Player/TestInventory.py
- tests/ai/tests/Player/TestPlayer.py
- tests/ai/tests/Utils/TestUtils.py
I added some tests to the AI part of the Zappy :
Current lines coverage :
Current branches coverage :
> Write unit tests to evaluate our AI algorithm - Zappy AI

- ai/src/AI.py
I added a check to be sure that the file are present before removing them.
*Big thank you to @mathieurobert1, without whom this pr would not have seen the day*
> Remove unsafe removing of log files - Zappy AI

- server/src/parsing/parse_frequency.c
I've limited frequency to avoid bug of gui because the game is to fast !
> fix: frequency is limited
